---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello from ConfigMap!</title>
    </head>
    <body>
      <h1>Hello Kubernetes!</h1>
      <p>This page is served by nginx, and content comes from a ConfigMap.</p>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
        - name: multitool
          image: praqma/network-multitool
          command: ["/bin/sh", "-c"]
          args: ["while true; do echo Multitool is running; sleep 10; done"]
      volumes:
        - name: html-volume
          configMap:
            name: nginx-html

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
spec:
  selector:
    app: nginx-multitool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
