apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-logs
spec:
  selector:
    matchLabels:
      app: multitool-logs
  template:
    metadata:
      labels:
        app: multitool-logs
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool
        command: ["/bin/sh", "-c"]
        args:
          - while true; do
              echo "=== Reading syslog ===";
              tail -n 10 /var/log/syslog;
              sleep 10;
            done
        volumeMounts:
        - name: syslog
          mountPath: /var/log/syslog
          readOnly: true
      volumes:
      - name: syslog
        hostPath:
          path: /var/log/syslog
          type: File
